pipeline {
    agent any

    environment {
        IMAGE_NAME = "payment-service"
        CONTAINER_NAME = "payment-service"
        PORT = "8081"
    }

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/for-hygge/payment-service.git'
            }
        }

        stage('Build (Simulated)') {
            steps {
                echo 'Building payment-service (simulated)'
            }
        }

        stage('Test (Simulated)') {
            steps {
                echo 'Running payment-service tests (simulated)'
            }
        }

        stage('Docker Build (Simulated)') {
            steps {
                echo "docker build -t ${IMAGE_NAME} ."
            }
        }

        stage('Deploy (Simulated)') {
            steps {
                echo "docker stop ${CONTAINER_NAME} || true"
                echo "docker rm ${CONTAINER_NAME} || true"
                echo "docker run -d -p ${PORT}:${PORT} --name ${CONTAINER_NAME} ${IMAGE_NAME}"
            }
        }
    }
}